// <auto-generated />
namespace Talabatak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StoresChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoresChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202112301749231_StoresChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
